# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  # trigger on changes to main branch and /src directory
  push:  
    branches: [ "main" ]
    paths: [ "src/**" ]
  # ..and on all pull requests   
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
    - name: Build jose.jar with Ant
      run: ant -noinput -buildfile build.xml
    - name: Build patch file
      run: ant -buildfile pack.xml patch -Dversion=latest -Ddist-dir=.

#    - name: 'Upload Artifact'
#      uses: actions/upload-artifact@v4
#      with:
#        path: packages/jose-Latest-patch.zip

    - name: 'Release Artifact'
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Draft
        body: built from latest sources; apply to one of the 1.5.2 packages.
        prerelease: true
        tag_name: Latest
        files: packages/jose-latest-patch.zip
        
